;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-reader.ss" "lang")((modname MrRobotQuote) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #f)))
(require 2htdp/image)

(overlay (beside (overlay (triangle 100 "outline" "red")
                          (triangle 80 "outline" "red")
                          (triangle 60 "outline" "red")
                          (triangle 40 "outline" "red"))
                 (rectangle 20 40 "solid" "black")
                 (above (circle 20 "solid" "red")
                        (circle 15 "outline" "red")
                        (circle 10 "solid" "red")
                        (rectangle 40 20 "solid" "black")
                        (above (text "A BUG IS NEVER JUST A MISTAKE." 24 "white")
                               (text "IT REPRESENTS SOMETHING BIGGER." 24 "white")
                               (text "AN ERROR OF THINKING." 24 "white")
                               (text "THAT MAKES WHO YOU ARE." 24 "white"))
                 (rectangle 40 20 "solid" "black")
                 (circle 10 "solid" "red")
                 (circle 15 "outline" "red")
                 (circle 20 "solid" "red"))
                 (rectangle 20 40 "solid" "black")
                 (overlay (triangle 100 "outline" "red")
                          (triangle 80 "outline" "red")
                          (triangle 60 "outline" "red")
                          (triangle 40 "outline" "red")))
         (rectangle 800 400 "solid" "black"))
